name: magritte
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - yt
  - scipy
  - vtk
  - mpi4py
  - plotly
  - pyyaml
  - ipywidgets
  - meshio
  - tqdm
  - python=3.6
  - palettable
  - h5py
  - numba
  - healpy
  - jupyterlab-plotly-extension
  - nbdime
  - jupyterlab-git
  - pandas
  - nodejs
  - twine
  - sphinx
  - breathe
  - sphinx-copybutton
  - nbsphinx
  - sphinx_rtd_theme
