name: magritte
channels:
  - conda-forge
  - anaconda
  - defaults
# The order of the channels above is critical!!!
dependencies:
  - python=3.9
  - cmake
  - k3d
  - numpy=1.23 #Temporary error with numba calling numpy calling ufunc with no exceptions in latest numpy; see https://github.com/numba/numba/issues/8615
  - vtk
  - jupyterlab
  - yt
  - scipy
  - mpi4py
  - plotly
  - pyyaml
  - ipywidgets
  - meshio=5.2
  - tqdm
  - palettable
  - h5py
  - numba
  - healpy
  - astroquery
  - jupyterlab-plotly-extension
  - nbdime
  - jupyterlab-git
  - pandas
  - nodejs
  - twine
  - sphinx=4.4.0
  - breathe
  - sphinx-copybutton
  - nbsphinx
  - sphinx_rtd_theme
  - pytest
