name: magrittedocs
channels:
  - ensor
  - conda-forge
  - anaconda
  - defaults
# The order of the channels above is critical!!!
dependencies:
  - python>=3.9
  - cmake
  - numpy
  - jupyterlab
  - yt
  - scipy
  - mpi4py
  - plotly
  - pyyaml
  - ipywidgets
  - tqdm
  - palettable
  - h5py
  - numba
  - healpy
  - astroquery
  - jupyterlab-plotly-extension
  - nbdime
  - jupyterlab-git
  - pandas
  - nodejs
  - twine
  - sphinx
  - pip
  - pip:
    - breathe
    - sphinx_rtd_theme 
    ##install both with pip, otherwise it will install the wrong version, not compatible with sphinx
  - sphinx-copybutton
  - nbsphinx
  - pytest
  - plons #for importing Phantom models
