name: magritte
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - meshio
  - h5py
  - healpy
  - jupyterlab
  - vtk
  - yt
  - scipy
  - numba
  - mpi4py
  - pyyaml
  - tqdm
  - ipywidgets
